#!/bin/bash
# enableSSH (UNIX exec.)
# enables ssh for $adminUser
# Last Edited: 6/25/18

### VARIABLES
source /usr/local/massmgmt/lib/massmgmtlib.sh

sshCheck="$(systemsetup getremotelogin | awk '/Remote/ {print $(3) }')"
scriptEnabled="$(cat $configFile | awk '/EnableSSH/ {print $2}')"

### SCRIPT
# check if the script is enabled in the config file
if [ "$scriptEnabled" == "Disable" ] ; then
	echo "$logStart enableSSH is disabled in the configuration file" >> "$logFile"
	if [ "$sshCheck" == "On" ] ; then
 		echo "$logStart SSH disabled but is on, turning off SSH" >> "$logFile"
		systemsetup setremotelogin off
		systemsetup setremotelogin off
	else
		echo "$logStart SSH is disabled" >> "$logFile"
	fi
	exit
elif [ "$scriptEnabled" == "Enable" ] ; then
	if [ "$sshCheck" == "On" ] ; then
		echo "$logStart SSH was already set to On" >> "$logFile"
	elif [ "$sshCheck" == "Off" ] ; then
		echo "$logStart SSH set to Off" >> "$logFile"
		userID="$(/usr/bin/dscl localhost -read /Local/Default/Users/$adminUser | grep GeneratedUID | awk '{print $2}')"
		if [ "$userID" != "" ] ; then
			echo "$logStart Granting SSH Access for $adminUser with GUID $userID" >> "$logFile"
			/usr/bin/dscl localhost -create /Local/Default/Groups/com.apple.access_ssh
			/usr/bin/dscl localhost -append /Local/Default/Groups/com.apple.access_ssh GroupMembership "$adminUser"
			/usr/bin/dscl localhost -append /Local/Default/Groups/com.apple.access_ssh GroupMembers "$userID"
			/usr/bin/dscl localhost -append /Local/Default/Groups/com.apple.access_ssh RealName 'Remote Login Group'
			/usr/bin/dscl localhost -append /Local/Default/Groups/com.apple.access_ssh PrimaryGroupID 104
			systemsetup setremotelogin on
			echo "$logStart SSH set to On" >> "$logFile"
		else
			echo "$logStart No record was found for $adminUser" >> "$logFile"
		fi
	else
        	echo "$logStart Failed, exiting" >> "$logFile"
	fi
else
	echo "$logStart Invalid enableSSH configuration" >> "$logFile"
fi
exit
