#!/bin/bash
# -----------------------------------------------------------------------------
# setName (UNIX exec.)
# set Hostname
# Last Edited: 6/16/18
# -----------------------------------------------------------------------------
source /usr/local/massmgmt/lib/massmgmtlib.sh

scriptEnabled="$(cat $configFile | awk '/SetHostname/ {print $2}')"
hostnameScheme="$(cat $configFile | awk '/HostnameFormat/ {print $2}')"
# Script Contents -------------------------------------------------------------
if [ "$scriptEnabled" == "Disable" ] ; then
    echo "$logStart setHostname disabled" >> "$logFile"
    exit
elif [ "$scriptEnabled" == "Enable" ] ; then
    echo "$logStart setHostname enabled" >> "$logFile"
    if [ "$hostnameScheme" == "Serial" ] ; then
	serial="$(/usr/sbin/system_profiler SPHardwareDataType | /usr/bin/awk '/Serial\ Number\ \(system\)/ {print $NF}')"
	if [ "$hostName" == "$serial" ] ; then
    	    echo "$logStart The computer hostname already set to serial number, exiting" >> "$logFile"
	else
    	    scutil --set ComputerName $serial
    	    scutil --set HostName $serial
    	    scutil --set LocalHostName $serial
    	    echo "$logStart Computer hostname set to $serial, exiting" >> "$logFile"
	fi
    else
	echo "$logStart non-serial hostname format. Implement this feature" >> "$logFile"
    fi
else
    echo "$logStart Invalid setHostname configuration" >> "$logFile"
fi
exit
# -----------------------------------------------------------------------------
